apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-config-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: mohawkiotlab/python-config-test:latest
        imagePullPolicy: Always